package com.finance.manager.repository;

import com.finance.manager.Expense;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import java.util.List;

/**
 * Spring Data JPA repository for {@link Expense}.
 * All SQL is generated by Hibernate — no manual JDBC or PreparedStatements.
 */
public interface ExpenseRepository extends JpaRepository<Expense, Long> {

    /** Returns all expenses newest-first (matches previous SQLite ordering). */
    List<Expense> findAllByOrderByDateDescIdDesc();

    /** Case-insensitive category filter — used by analytics. */
    List<Expense> findByCategoryIgnoreCase(String category);

    /** Aggregate sum used for budget progress. Returns 0 when table is empty. */
    @Query("SELECT COALESCE(SUM(e.amount), 0) FROM Expense e")
    Double sumAllAmounts();
}
